export const SLACK_CONFIG_OPTIONS = 'SLACK_CONFIG_OPTIONS';
export const SLACK_INTERACTIVITY_HANDLER = 'SLACK_INTERACTIVITY_HANDLER';
export const SLACK_EVENT_HANDLER = 'SLACK_EVENT_HANDLER';
export const SLACK_CLIENT = 'SLACK_CLIENT';
